### PR TITLE
Update to Material 2.0.0-alpha.7-4

### PR DESCRIPTION
**Pull request by Nightapes**
* update to Material 2.0.0-alpha.7-4
* clean up
* add Material 2 Module (for all components)

### CODE REVIEW

**Comment by JohnnyQQQQ** [comment]
very good work :+1:  could you try to fix the build?

**Comment by JohnnyQQQQ** [comment]
I think you just need to add 'typings/main/ambient/hammerjs/hammerjs.d.ts' to the task building the javascript. I.E. https://github.com/DeviantJS/angular2-seed-material2/blob/master/tools/tasks/seed/build.js.e2e.ts line 17

**Comment by JohnnyQQQQ** [comment]
@d3viant0ne could you review this one too :+1:

**Comment by Nightapes** [comment]
Yes, the problem was that it was running locally , because i had an old typings version and `hammerjs` as ambientDependencies. Moved it to global and it's working now.

**Comment by Nightapes** [comment]
Without the declaration the `prod.build` was failing.
It tries to load `node_modules/card.js `which does not exists and fails. 
When there is a better solution, maybe you can give me a small hint to fix it.

**Comment by JohnnyQQQQ** [comment]
Mh, I just checked out your PR and could `build.prod` without those packages.. strange

**Comment by Nightapes** [comment]
Under Linux it is working fine for me too. Under Windows 10 not.

**Comment by JohnnyQQQQ** [comment]
This makes sense, I could build it on Linux without any of those packages, so I think they are only needed on Windows

**Comment by JohnnyQQQQ** [comment]
I did some digging in git and found out that the packages were added on commit 5a251578cadc650b71c8b7b848e779f2b8218508, for this issue https://github.com/mgechev/angular2-seed/issues/831 , so everything perfectly fine :rocket: again nice work

**Pull request merged**
